#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_enums.py; DO NOT HAND-MODIFY */


template<typename T>
    T get_enum(const char *e);


// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

enum class placement
{
    full_block_snapped = 0,
    half_block_snapped = 1,
    quarter_block_snapped = 2,
    eighth_block_snapped = 3,
    invalid = -1,
};

const char* get_enum_string(placement value);

template<> placement get_enum<placement>(const char *e);

// -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

enum class rotation
{
    axis_aligned = 0,
    rot_45 = 1,
    rot_15 = 2,
    invalid = -1,
};

const char* get_enum_string(rotation value);

template<> rotation get_enum<rotation>(const char *e);
