/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <algorithm>
#include <string.h>
#include <memory>

#include "../memory.h"
#include "builder_component.h"
#include "component_system_manager.h"

extern component_system_manager component_system_man;

void
builder_component_manager::create_component_instance_data(unsigned count) {
    if (count <= buffer.allocated)
        return;

    component_buffer new_buffer{};
    instance_data new_pool{};

    size_t size = sizeof(c_entity) * count;
    size = sizeof(float) * count + align_size<float>(size);
    size = sizeof(float) * count + align_size<float>(size);
    size = sizeof(glm::vec3) * count + align_size<glm::vec3>(size);
    size = sizeof(int) * count + align_size<int>(size);
    size += 16;   // for worst-case misalignment of initial ptr

    new_buffer.buffer = malloc(size);
    new_buffer.num = buffer.num;
    new_buffer.allocated = count;
    memset(new_buffer.buffer, 0, size);

    new_pool.entity = align_ptr((c_entity *)new_buffer.buffer);
    new_pool.speed = align_ptr((float *)(new_pool.entity + count));
    new_pool.rot_speed = align_ptr((float *)(new_pool.speed + count));
    new_pool.desired_pos = align_ptr((glm::vec3 *)(new_pool.rot_speed + count));
    new_pool.build_index = align_ptr((int *)(new_pool.desired_pos + count));

    memcpy(new_pool.entity, instance_pool.entity, buffer.num * sizeof(c_entity));
    memcpy(new_pool.speed, instance_pool.speed, buffer.num * sizeof(float));
    memcpy(new_pool.rot_speed, instance_pool.rot_speed, buffer.num * sizeof(float));
    memcpy(new_pool.desired_pos, instance_pool.desired_pos, buffer.num * sizeof(glm::vec3));
    memcpy(new_pool.build_index, instance_pool.build_index, buffer.num * sizeof(int));

    free(buffer.buffer);
    buffer = new_buffer;

    instance_pool = new_pool;
}

void
builder_component_manager::destroy_instance(instance i) {
    auto last_index = buffer.num - 1;
    auto last_entity = instance_pool.entity[last_index];
    auto current_entity = instance_pool.entity[i.index];

    instance_pool.entity[i.index] = instance_pool.entity[last_index];
    instance_pool.speed[i.index] = instance_pool.speed[last_index];
    instance_pool.rot_speed[i.index] = instance_pool.rot_speed[last_index];
    instance_pool.desired_pos[i.index] = instance_pool.desired_pos[last_index];
    instance_pool.build_index[i.index] = instance_pool.build_index[last_index];

    entity_instance_map[last_entity] = i.index;
    entity_instance_map.erase(current_entity);

    --buffer.num;
}

void
builder_component_manager::entity(c_entity e) {
    if (buffer.num >= buffer.allocated) {
        printf("Increasing size of builder buffer. Please adjust\n");
        create_component_instance_data(std::max(1u, buffer.allocated) * 2);
    }

    auto inst = lookup(e);

    instance_pool.entity[inst.index] = e;
}

void
builder_component_stub::assign_component_to_entity(c_entity entity) {
    auto &man = component_system_man.managers.builder_component_man;

    man.assign_entity(entity);

    auto data = man.get_instance_data(entity);        

    *data.speed = 10;

    *data.rot_speed = 10;

    *data.desired_pos = glm::vec3{0};

    *data.build_index = 0;

    *data.speed = speed;

    *data.rot_speed = rot_speed;
};

std::unique_ptr<component_stub> builder_component_stub::from_config(const config_setting_t *config) {
    auto builder_stub = std::make_unique<builder_component_stub>();

    auto speed_member = config_setting_get_member(config, "speed");
    builder_stub->speed = (float)config_setting_get_float(speed_member);

    auto rot_speed_member = config_setting_get_member(config, "rot_speed");
    builder_stub->rot_speed = (float)config_setting_get_float(rot_speed_member);

    return std::move(builder_stub);
}
