#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "component_system_manager.h"

extern component12_system_manager component_system_man;

struct door_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        const char* *mesh;
        float *pos;
        float *desired_pos;
        int *height;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.mesh = instance_pool.mesh + inst.index;
        d.pos = instance_pool.pos + inst.index;
        d.desired_pos = instance_pool.desired_pos + inst.index;
        d.height = instance_pool.height + inst.index;

        return d;
    }
};

struct door_component_stub : component_stub {
    door_component_stub() : component_stub("door") {}

    void
    assign_component_to_entity(c_entity entity) override {
        auto &man = component_system_man.managers.door_component_man;

        man.assign_entity(entity);
        auto data = man.get_instance_data(entity);        

        *data.mesh = nullptr;

        *data.pos = 1;

        *data.desired_pos = 1;

        *data.height = 2;
  };
};
