/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <algorithm>
#include <string.h>
#include <memory>

#include "../memory.h"
#include "gas_producer_component.h"
#include "component_system_manager.h"

extern component_system_manager component_system_man;

void
gas_producer_component_manager::create_component_instance_data(unsigned count) {
    if (count <= buffer.allocated)
        return;

    component_buffer new_buffer{};
    instance_data new_pool{};

    size_t size = sizeof(c_entity) * count;
    size = sizeof(unsigned) * count + align_size<unsigned>(size);
    size = sizeof(float) * count + align_size<float>(size);
    size = sizeof(float) * count + align_size<float>(size);
    size = sizeof(bool) * count + align_size<bool>(size);
    size += 16;   // for worst-case misalignment of initial ptr

    new_buffer.buffer = malloc(size);
    new_buffer.num = buffer.num;
    new_buffer.allocated = count;
    memset(new_buffer.buffer, 0, size);

    new_pool.entity = align_ptr((c_entity *)new_buffer.buffer);
    new_pool.gas_type = align_ptr((unsigned *)(new_pool.entity + count));
    new_pool.flow_rate = align_ptr((float *)(new_pool.gas_type + count));
    new_pool.max_pressure = align_ptr((float *)(new_pool.flow_rate + count));
    new_pool.enabled = align_ptr((bool *)(new_pool.max_pressure + count));

    memcpy(new_pool.entity, instance_pool.entity, buffer.num * sizeof(c_entity));
    memcpy(new_pool.gas_type, instance_pool.gas_type, buffer.num * sizeof(unsigned));
    memcpy(new_pool.flow_rate, instance_pool.flow_rate, buffer.num * sizeof(float));
    memcpy(new_pool.max_pressure, instance_pool.max_pressure, buffer.num * sizeof(float));
    memcpy(new_pool.enabled, instance_pool.enabled, buffer.num * sizeof(bool));

    free(buffer.buffer);
    buffer = new_buffer;

    instance_pool = new_pool;
}

void
gas_producer_component_manager::destroy_instance(instance i) {
    auto last_index = buffer.num - 1;
    auto last_entity = instance_pool.entity[last_index];
    auto current_entity = instance_pool.entity[i.index];

    instance_pool.entity[i.index] = instance_pool.entity[last_index];
    instance_pool.gas_type[i.index] = instance_pool.gas_type[last_index];
    instance_pool.flow_rate[i.index] = instance_pool.flow_rate[last_index];
    instance_pool.max_pressure[i.index] = instance_pool.max_pressure[last_index];
    instance_pool.enabled[i.index] = instance_pool.enabled[last_index];

    entity_instance_map[last_entity] = i.index;
    entity_instance_map.erase(current_entity);

    --buffer.num;
}

void
gas_producer_component_manager::entity(c_entity e) {
    if (buffer.num >= buffer.allocated) {
        printf("Increasing size of gas_producer buffer. Please adjust\n");
        create_component_instance_data(std::max(1u, buffer.allocated) * 2);
    }

    auto inst = lookup(e);

    instance_pool.entity[inst.index] = e;
}

void
gas_producer_component_stub::assign_component_to_entity(c_entity entity) {
    auto &man = component_system_man.managers.gas_producer_component_man;

    man.assign_entity(entity);

    auto data = man.get_instance_data(entity);        

    *data.gas_type = 0;

    *data.flow_rate = 0.1;

    *data.max_pressure = 1.0;

    *data.enabled = true;

    *data.gas_type = gas_type;

    *data.flow_rate = flow_rate;

    *data.max_pressure = max_pressure;
};

std::unique_ptr<component_stub> gas_producer_component_stub::from_config(const config_setting_t *config) {
    auto gas_producer_stub = std::make_unique<gas_producer_component_stub>();

    auto gas_type_member = config_setting_get_member(config, "gas_type");
    gas_producer_stub->gas_type = config_setting_get_int(gas_type_member);

    auto flow_rate_member = config_setting_get_member(config, "flow_rate");
    gas_producer_stub->flow_rate = config_setting_get_float(flow_rate_member);

    auto max_pressure_member = config_setting_get_member(config, "max_pressure");
    gas_producer_stub->max_pressure = config_setting_get_float(max_pressure_member);

    return std::move(gas_producer_stub);
}

std::vector<std::string> gas_producer_component_stub::get_dependencies() {
    return {
        "power", "wire_comms", 
    };
}
