#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include "component_manager.h"

struct gas_production_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        unsigned *gas_type;
        float *flow_rate;
        float *max_pressure;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    unsigned & gas_type(c_entity e) {
        auto inst = lookup(e);
        return instance_pool.gas_type[inst.index];
    }
    float & flow_rate(c_entity e) {
        auto inst = lookup(e);
        return instance_pool.flow_rate[inst.index];
    }
    float & max_pressure(c_entity e) {
        auto inst = lookup(e);
        return instance_pool.max_pressure[inst.index];
    }
};
