#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "component_system_manager.h"

extern component12_system_manager component_system_man;

struct gas_producer_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        unsigned *gas_type;
        float *flow_rate;
        float *max_pressure;
        bool *enabled;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.gas_type = instance_pool.gas_type + inst.index;
        d.flow_rate = instance_pool.flow_rate + inst.index;
        d.max_pressure = instance_pool.max_pressure + inst.index;
        d.enabled = instance_pool.enabled + inst.index;

        return d;
    }
};

struct gas_producer_component_stub : component_stub {
    gas_producer_component_stub() : component_stub("gas_producer") {}

    unsigned gas_type{};

    float flow_rate{};

    float max_pressure{};

    void
    assign_component_to_entity(c_entity entity) override {
        auto &man = component_system_man.managers.gas_producer_component_man;

        man.assign_entity(entity);
        auto data = man.get_instance_data(entity);        

        *data.gas_type = 0;

        *data.flow_rate = 0.1;

        *data.max_pressure = 1.0;

        *data.enabled = true;

        *data.gas_type = gas_type;

        *data.flow_rate = flow_rate;

        *data.max_pressure = max_pressure;
  };
};
