/* THIS FILE IS AUTOGENERATED BY gen/gen_comps.py; DO NOT HAND-MODIFY */

#include <algorithm>
#include <string.h>
#include <memory>

#include "../memory.h"
#include "position_component.h"
#include "component_system_manager.h"

extern component_system_manager component_system_man;

void
position_component_manager::create_component_instance_data(unsigned count) {
    if (count <= buffer.allocated)
        return;

    component_buffer new_buffer{};
    instance_data new_pool{};

    size_t size = sizeof(c_entity) * count;
    size = sizeof(glm::mat4) * count + align_size<glm::mat4>(size);
    size += 16;   // for worst-case misalignment of initial ptr

    new_buffer.buffer = malloc(size);
    new_buffer.num = buffer.num;
    new_buffer.allocated = count;
    memset(new_buffer.buffer, 0, size);

    new_pool.entity = align_ptr((c_entity *)new_buffer.buffer);
    new_pool.mat = align_ptr((glm::mat4 *)(new_pool.entity + count));

    memcpy(new_pool.entity, instance_pool.entity, buffer.num * sizeof(c_entity));
    memcpy(new_pool.mat, instance_pool.mat, buffer.num * sizeof(glm::mat4));

    free(buffer.buffer);
    buffer = new_buffer;

    instance_pool = new_pool;
}

void
position_component_manager::destroy_instance(instance i) {
    auto last_index = buffer.num - 1;
    auto last_entity = instance_pool.entity[last_index];
    auto current_entity = instance_pool.entity[i.index];

    instance_pool.entity[i.index] = instance_pool.entity[last_index];
    instance_pool.mat[i.index] = instance_pool.mat[last_index];

    entity_instance_map[last_entity] = i.index;
    entity_instance_map.erase(current_entity);

    --buffer.num;
}

void
position_component_manager::entity(c_entity e) {
    if (buffer.num >= buffer.allocated) {
        printf("Increasing size of position buffer. Please adjust\n");
        create_component_instance_data(std::max(1u, buffer.allocated) * 2);
    }

    auto inst = lookup(e);

    instance_pool.entity[inst.index] = e;
}

void
position_component_stub::assign_component_to_entity(c_entity entity) {
    auto &man = component_system_man.managers.position_component_man;

    man.assign_entity(entity);

    auto data = man.get_instance_data(entity);

    *data.mat = glm::mat4(0);
};

std::unique_ptr<component_stub> position_component_stub::from_config(const config_setting_t *config) {
    auto position_stub = std::make_unique<position_component_stub>();


    return std::move(position_stub);
}

std::vector<std::string> position_component_stub::get_dependencies() {
    return {
    };
}
