#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_comps.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "../enums/enums.h"

struct power_provider_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        float *max_provided;
        float *provided;
        unsigned *network;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.max_provided = instance_pool.max_provided + inst.index;
        d.provided = instance_pool.provided + inst.index;
        d.network = instance_pool.network + inst.index;

        return d;
    }
};

struct power_provider_component_stub : component_stub {
    power_provider_component_stub() = default;

    float max_provided{};

    void
    assign_component_to_entity(c_entity entity) override;

    static std::unique_ptr<component_stub> from_config(config_setting_t const *config);

    std::vector<std::string>
    get_dependencies() override;
};
