#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include "component_manager.h"

struct power_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        unsigned *required_power;
        bool *powered;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    unsigned & required_power(c_entity e) {
        auto inst = lookup(e);
        return instance_pool.required_power[inst.index];
    }
    bool & powered(c_entity e) {
        auto inst = lookup(e);
        return instance_pool.powered[inst.index];
    }
};
