#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "component_system_manager.h"

extern component12_system_manager component_system_man;

struct pressure_sensor_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        float *pressure;
        unsigned *type;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.pressure = instance_pool.pressure + inst.index;
        d.type = instance_pool.type + inst.index;

        return d;
    }
};

struct pressure_sensor_component_stub : component_stub {
    pressure_sensor_component_stub() : component_stub("pressure_sensor") {}

    unsigned type{};

    void
    assign_component_to_entity(c_entity entity) override {
        auto &man = component_system_man.managers.pressure_sensor_component_man;

        man.assign_entity(entity);
        auto data = man.get_instance_data(entity);        

        *data.pressure = 0;

        *data.type = 0;

        *data.type = type;
  };
};
