#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"

struct proximity_sensor_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        float *range;
        bool *is_detected;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.range = instance_pool.range + inst.index;

        d.is_detected = instance_pool.is_detected + inst.index;

        return d;
    }
};

struct proximity_sensor_component_stub : component_stub {
    proximity_sensor_component_stub() = default;

    float range{};

    void
    assign_component_to_entity(c_entity entity) override;

    static
    std::unique_ptr<component_stub>
    from_config(const config_setting_t *proximity_sensor_config) {
        auto proximity_sensor_stub = std::make_unique<proximity_sensor_component_stub>();

        auto range_member = config_setting_get_member(proximity_sensor_config, "range");
        proximity_sensor_stub->range = config_setting_get_float(range_member);

        return std::move(proximity_sensor_stub);
    }
};
