#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"

struct relative_position_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        glm::vec3 *position;
        glm::mat4 *mat;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    void register_stub_generator();

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.position = instance_pool.position + inst.index;
        d.mat = instance_pool.mat + inst.index;

        return d;
    }

    static relative_position_component_manager* get_manager() {
        return dynamic_cast<relative_position_component_manager*>(::component_managers["relative_position"].get());
    }
};

struct relative_position_component_stub : component_stub {
    relative_position_component_stub() : component_stub("relative_position") {}

    void
    assign_component_to_entity(c_entity entity) override {
        auto man = dynamic_cast<relative_position_component_manager*>(std::move(::component_managers[component_name]).get());

        man->assign_entity(entity);
        auto data = man->get_instance_data(entity);        

        *data.position = glm::vec3(0);

        *data.mat = glm::mat4(0);
  };
};
