#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_comps.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "../enums/enums.h"
#include "wire_filter.h"

struct rotator_component_manager : component_manager<rotator_component_manager> {
    struct instance_data {
        c_entity *entity;
        wire_filter_ptr *filter;
        glm::vec3 *rot_axis;
        int *rot_dir;
        float *rot_speed;
        float *rot_cur_speed;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    static const char* get_ui_name() {
        return "Rotator";
    }

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.filter = instance_pool.filter + inst.index;
        d.rot_axis = instance_pool.rot_axis + inst.index;
        d.rot_dir = instance_pool.rot_dir + inst.index;
        d.rot_speed = instance_pool.rot_speed + inst.index;
        d.rot_cur_speed = instance_pool.rot_cur_speed + inst.index;

        return d;
    }
};

struct rotator_component_stub : component_stub {
    rotator_component_stub() = default;

    glm::vec3 rot_axis{};
    int rot_dir{};
    float rot_speed{};

    void
    assign_component_to_entity(c_entity entity) override;

    static std::unique_ptr<component_stub> from_config(config_setting_t const *config);

    std::vector<std::string>
    get_dependencies() override;
};
