#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_comps.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "../enums/enums.h"
#include "wire_filter.h"

struct sensor_comparator_component_manager : component_manager<sensor_comparator_component_manager> {
    struct instance_data {
        c_entity *entity;
        float *compare_result;
        float *compare_epsilon;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    static const char* get_ui_name() {
        return "Sensor Comparator";
    }

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.compare_result = instance_pool.compare_result + inst.index;
        d.compare_epsilon = instance_pool.compare_epsilon + inst.index;

        return d;
    }
};

struct sensor_comparator_component_stub : component_stub {
    sensor_comparator_component_stub() = default;

    float compare_epsilon{};

    void
    assign_component_to_entity(c_entity entity) override;

    static std::unique_ptr<component_stub> from_config(config_setting_t const *config);

    std::vector<std::string>
    get_dependencies() override;
};
