#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"
#include "component_system_manager.h"

extern component12_system_manager component_system_man;

struct sensor_comparator_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        float *compare_result;
        float *compare_epsilon;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.compare_result = instance_pool.compare_result + inst.index;
        d.compare_epsilon = instance_pool.compare_epsilon + inst.index;

        return d;
    }
};

struct sensor_comparator_component_stub : component_stub {
    sensor_comparator_component_stub() : component_stub("sensor_comparator") {}

    float compare_epsilon{};

    void
    assign_component_to_entity(c_entity entity) override {
        auto &man = component_system_man.managers.sensor_comparator_component_man;

        man.assign_entity(entity);
        auto data = man.get_instance_data(entity);        

        *data.compare_result = 0;

        *data.compare_epsilon = 0;

        *data.compare_epsilon = compare_epsilon;
  };
};
