#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"

struct surface_attachment_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        glm::ivec3 *block;
        int *face;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.block = instance_pool.block + inst.index;

        d.face = instance_pool.face + inst.index;

        return d;
    }
};

struct surface_attachment_component_stub : component_stub {
    surface_attachment_component_stub() = default;

    void
    assign_component_to_entity(c_entity entity) override;

    static
    std::unique_ptr<component_stub>
    from_config(const config_setting_t *surface_attachment_config) {
        auto surface_attachment_stub = std::make_unique<surface_attachment_component_stub>();

        return std::move(surface_attachment_stub);
    }
};
