#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>

#include "component_manager.h"

struct surface_attachment_component_stub : component_stub {
    static void register_generator();
};

struct surface_attachment_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        glm::ivec3 *block;
        int *face;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    instance_data get_instance_data(c_entity e) {
        instance_data d;
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.block = instance_pool.block + inst.index;
        d.face = instance_pool.face + inst.index;

        return d;
    }
};
