#pragma once

/* THIS FILE IS AUTOGENERATED BY gen/gen_component_impl.py; DO NOT HAND-MODIFY */

#include <libconfig.h>
#include <memory>

#include "component_manager.h"

struct switch_component_manager : component_manager {
    struct instance_data {
        c_entity *entity;
        bool *enabled;
    } instance_pool;

    void create_component_instance_data(unsigned count) override;
    void destroy_instance(instance i) override;
    void entity(c_entity e) override;

    void register_stub_generator();

    instance_data get_instance_data(c_entity e) {
        instance_data d{};
        auto inst = lookup(e);

        d.entity = instance_pool.entity + inst.index;
        d.enabled = instance_pool.enabled + inst.index;

        return d;
    }

    static switch_component_manager* get_manager() {
        return dynamic_cast<switch_component_manager*>(component_managers["switch"].get());
    }
};

struct switch_component_stub : component_stub {
    switch_component_stub() : component_stub("switch") {}

    void
    assign_component_to_entity(c_entity entity) {
        std::shared_ptr<component_manager> m = std::move(component_managers[name]);
        std::shared_ptr<switch_component_manager> man = std::dynamic_pointer_cast<switch_component_manager>(m);

        man->assign_entity(entity);
        auto data = man->get_instance_data(entity);        

        *data.enabled = false;
  };
};
